x-baseService: &baseService
  restart: always
  healthcheck:
    interval: 1s
    timeout: 2s
    retries: 100

services:
  loc-gateway:
    <<: *baseService
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports: 
      - ${GATEWAY_PORT}:80
    depends_on:
      loc-backend:
        condition: service_healthy
      loc-frontend:
        condition: service_healthy
      loc-adminer:
        condition: service_started

  loc-db:
    <<: *baseService
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_HOST} -U ${DB_USER}"]
    volumes:
      - ./persist/loc-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}

  loc-adminer:
    <<: *baseService
    image: adminer
    depends_on:
      loc-db:
        condition: service_healthy

  loc-backend:
    <<: *baseService
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    healthcheck: 
      test: ["CMD-SHELL", "curl --fail --request POST --header 'Content-Type: application/json' --url 'http://loc-backend:4000' --data '{\"query\":\"query { __typename }\"}' || exit 1"]
    depends_on:
      loc-db:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src/
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_TTL: ${COOKIE_TTL}

  loc-frontend:
    <<: *baseService
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    healthcheck: 
      test: ["CMD-SHELL", "curl --fail --request GET --url 'http://loc-frontend:5173' || exit 1"]
    depends_on:
      loc-codegen:
        condition: service_completed_successfully
    volumes:
      - ./frontend/src:/app/src/
    environment:
      VITE_API_URL: ${VITE_API_URL}

  loc-codegen:
    <<: *baseService
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      loc-backend:
        condition: service_healthy
    volumes:
      - ./frontend/src:/app/src/
    command: ["npm", "run", "codegen"]
    environment:
      VITE_API_URL: http://loc-backend:4000