x-baseService: &baseService
  restart: always
  healthcheck:
    interval: 1s
    timeout: 2s
    retries: 100

services:
  prd-gateway:
    <<: *baseService
    image: nginx:1.21.3
    volumes:
      - ./nginx.prd.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./persist/prd-nginx:/var/log/nginx
    ports: 
      - ${GATEWAY_PORT}:80
    depends_on:
      prd-backend:
        condition: service_healthy
      prd-frontend:
        condition: service_healthy

  prd-db:
    <<: *baseService
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_HOST} -U ${DB_USER}"]
    volumes:
      - ./persist/prd-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}

  prd-backend:
    <<: *baseService
    image: ${DOCKER_HUB_USERNAME}/${APP_NAME}-backend
    command: sh -c "npm run start"
    healthcheck: 
      test: ["CMD-SHELL", "curl --fail --request POST --header 'Content-Type: application/json' --url 'http://prd-backend:4000' --data '{\"query\":\"query { __typename }\"}' || exit 1"]
    depends_on:
      prd-db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      SERVER_PORT: 4000

  prd-frontend:
    <<: *baseService
    image: ${DOCKER_HUB_USERNAME}/${APP_NAME}-frontend
    healthcheck: 
      test: ["CMD-SHELL", "curl --fail --request GET --url 'http://prd-frontend:4001' || exit 1"]
    volumes:
      - web-client-build:/app/build
    environment:
      NODE_ENV: production
      SERVER_PORT: 4001
      VITE_API_URL: http://prd-backend:4000

volumes:
  web-client-build: