x-baseService: &baseService
  restart: no
  healthcheck:
    interval: 1s
    timeout: 2s
    retries: 100

services:
  e2e-gateway:
    <<: *baseService
    image: nginx
    volumes:
      - ./nginx.e2e.conf:/etc/nginx/nginx.conf
    ports: 
      - ${GATEWAY_PORT}:80
    depends_on:
      e2e-backend:
        condition: service_healthy
      e2e-frontend:
        condition: service_healthy

  e2e-db:
    <<: *baseService
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_HOST} -U ${DB_USER}"]
    volumes:
      - ./persist/e2e-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}

  e2e-backend:
    <<: *baseService
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    healthcheck: 
      test: ["CMD-SHELL", "curl --fail --request POST --header 'Content-Type: application/json' --url 'http://e2e-backend:4000' --data '{\"query\":\"query { __typename }\"}' || exit 1"]
    depends_on:
      e2e-db:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src/
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_TTL: ${COOKIE_TTL}

  e2e-frontend:
    <<: *baseService
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    healthcheck: 
      test: ["CMD-SHELL", "curl --fail --request GET --url 'http://e2e-frontend:5173' || exit 1"]
    depends_on:
      e2e-codegen:
        condition: service_completed_successfully
    volumes:
      - ./frontend/src:/app/src/
    environment:
      VITE_API_URL: http://e2e-backend:4000

  e2e-codegen:
    <<: *baseService
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      e2e-backend:
        condition: service_healthy
    volumes:
      - ./frontend/src:/app/src/
    command: ["npm", "run codegen"]
    environment:
      VITE_API_URL: http://e2e-backend:4000

  e2e-tests:
    <<: *baseService
    build:  
      context: ./e2e
      dockerfile: Dockerfile.dev
    volumes:
      - ./persist/e2e-playwright-report:/app/playwright-report
      - ./persist/e2e-tests-results:/app/tests-results
    depends_on:
      e2e-gateway:
        condition: service_started
    environment:
      WEBSITE_URL: http://e2e-gateway
